-- SIGO: venta transaccional + descuento de stock + movimiento de caja.
-- No modifica historicos existentes; agrega estructuras nuevas y una RPC atomica.

create table if not exists public.ventas_sigo (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete restrict,
  numero bigint generated by default as identity,
  estado text not null default 'confirmada' check (estado in ('confirmada','anulada')),
  medio_pago text not null default 'efectivo' check (medio_pago in ('efectivo','debito','credito','transferencia','cuenta_corriente','otro')),
  total numeric(14,2) not null check (total >= 0),
  idempotency_key text not null,
  created_by uuid not null default auth.uid() references auth.users(id) on delete restrict,
  created_at timestamptz not null default now(),
  unique (empresa_id, idempotency_key)
);

create table if not exists public.venta_items_sigo (
  id uuid primary key default gen_random_uuid(),
  venta_id uuid not null references public.ventas_sigo(id) on delete cascade,
  empresa_id uuid not null references public.empresas(id) on delete restrict,
  producto_id uuid not null references public.productos(id) on delete restrict,
  cantidad numeric(14,3) not null check (cantidad > 0),
  precio_unitario numeric(14,2) not null check (precio_unitario >= 0),
  subtotal numeric(14,2) not null check (subtotal >= 0)
);

create table if not exists public.caja_movimientos_sigo (
  id uuid primary key default gen_random_uuid(),
  empresa_id uuid not null references public.empresas(id) on delete restrict,
  venta_id uuid references public.ventas_sigo(id) on delete restrict,
  tipo text not null check (tipo in ('ingreso','egreso')),
  medio_pago text not null,
  importe numeric(14,2) not null check (importe >= 0),
  concepto text not null,
  created_by uuid not null default auth.uid() references auth.users(id) on delete restrict,
  created_at timestamptz not null default now()
);

create index if not exists ventas_sigo_empresa_fecha_idx on public.ventas_sigo(empresa_id, created_at desc);
create index if not exists venta_items_sigo_venta_idx on public.venta_items_sigo(venta_id);
create index if not exists caja_movimientos_sigo_empresa_fecha_idx on public.caja_movimientos_sigo(empresa_id, created_at desc);

alter table public.ventas_sigo enable row level security;
alter table public.venta_items_sigo enable row level security;
alter table public.caja_movimientos_sigo enable row level security;

drop policy if exists ventas_sigo_select on public.ventas_sigo;
create policy ventas_sigo_select on public.ventas_sigo for select to authenticated
using (public.tiene_permiso_empresa(empresa_id, 'sales.read'));

drop policy if exists venta_items_sigo_select on public.venta_items_sigo;
create policy venta_items_sigo_select on public.venta_items_sigo for select to authenticated
using (public.tiene_permiso_empresa(empresa_id, 'sales.read'));

drop policy if exists caja_movimientos_sigo_select on public.caja_movimientos_sigo;
create policy caja_movimientos_sigo_select on public.caja_movimientos_sigo for select to authenticated
using (public.tiene_permiso_empresa(empresa_id, 'sales.read'));

-- Escritura directa bloqueada: toda venta debe pasar por la RPC transaccional.
drop policy if exists ventas_sigo_insert_blocked on public.ventas_sigo;
create policy ventas_sigo_insert_blocked on public.ventas_sigo for insert to authenticated with check (false);
drop policy if exists venta_items_sigo_insert_blocked on public.venta_items_sigo;
create policy venta_items_sigo_insert_blocked on public.venta_items_sigo for insert to authenticated with check (false);
drop policy if exists caja_movimientos_sigo_insert_blocked on public.caja_movimientos_sigo;
create policy caja_movimientos_sigo_insert_blocked on public.caja_movimientos_sigo for insert to authenticated with check (false);

create or replace function public.confirmar_venta_sigo(
  p_empresa_id uuid,
  p_items jsonb,
  p_medio_pago text default 'efectivo',
  p_idempotency_key text default null
)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_venta_id uuid;
  v_item jsonb;
  v_producto record;
  v_cantidad numeric(14,3);
  v_total numeric(14,2) := 0;
  v_key text := nullif(trim(coalesce(p_idempotency_key, '')), '');
begin
  if v_user_id is null then raise exception 'AUTH_REQUIRED'; end if;
  if not public.tiene_permiso_empresa(p_empresa_id, 'sales.write') then raise exception 'SALES_WRITE_FORBIDDEN'; end if;
  if p_medio_pago not in ('efectivo','debito','credito','transferencia','cuenta_corriente','otro') then raise exception 'PAYMENT_METHOD_INVALID'; end if;
  if v_key is null then raise exception 'IDEMPOTENCY_KEY_REQUIRED'; end if;
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then raise exception 'SALE_ITEMS_REQUIRED'; end if;

  select id into v_venta_id from public.ventas_sigo where empresa_id = p_empresa_id and idempotency_key = v_key;
  if v_venta_id is not null then return v_venta_id; end if;

  insert into public.ventas_sigo (empresa_id, total, medio_pago, idempotency_key, created_by)
  values (p_empresa_id, 0, p_medio_pago, v_key, v_user_id)
  returning id into v_venta_id;

  for v_item in select value from jsonb_array_elements(p_items)
  loop
    v_cantidad := nullif((v_item->>'cantidad')::numeric, 0);
    if v_cantidad is null or v_cantidad <= 0 then raise exception 'SALE_QUANTITY_INVALID'; end if;

    select id, empresa_id, nombre, precio_venta, stock_actual
      into v_producto
      from public.productos
      where id = (v_item->>'producto_id')::uuid
        and empresa_id = p_empresa_id
      for update;

    if not found then raise exception 'PRODUCT_NOT_FOUND'; end if;
    if v_producto.precio_venta is null then raise exception 'PRODUCT_PRICE_REQUIRED: %', v_producto.nombre; end if;
    if v_producto.stock_actual is null then raise exception 'PRODUCT_STOCK_REQUIRED: %', v_producto.nombre; end if;
    if v_producto.stock_actual < v_cantidad then raise exception 'INSUFFICIENT_STOCK: %', v_producto.nombre; end if;

    insert into public.venta_items_sigo (venta_id, empresa_id, producto_id, cantidad, precio_unitario, subtotal)
    values (v_venta_id, p_empresa_id, v_producto.id, v_cantidad, v_producto.precio_venta, round(v_producto.precio_venta * v_cantidad, 2));

    update public.productos
      set stock_actual = stock_actual - v_cantidad
      where id = v_producto.id and empresa_id = p_empresa_id;

    v_total := v_total + round(v_producto.precio_venta * v_cantidad, 2);
  end loop;

  update public.ventas_sigo set total = v_total where id = v_venta_id;

  if p_medio_pago <> 'cuenta_corriente' then
    insert into public.caja_movimientos_sigo (empresa_id, venta_id, tipo, medio_pago, importe, concepto, created_by)
    values (p_empresa_id, v_venta_id, 'ingreso', p_medio_pago, v_total, 'Venta SIGO', v_user_id);
  end if;

  return v_venta_id;
exception
  when unique_violation then
    select id into v_venta_id from public.ventas_sigo where empresa_id = p_empresa_id and idempotency_key = v_key;
    if v_venta_id is not null then return v_venta_id; end if;
    raise;
end;
$$;

revoke all on function public.confirmar_venta_sigo(uuid, jsonb, text, text) from public;
grant execute on function public.confirmar_venta_sigo(uuid, jsonb, text, text) to authenticated;

comment on function public.confirmar_venta_sigo(uuid, jsonb, text, text) is
  'SIGO: confirma venta de forma atomica, toma precios del backend, valida stock, descuenta existencias y registra caja. Idempotente por empresa.';
